# Generated by Django 4.2 on 2023-05-05 15:46

from django.db import migrations, models
import django.db.models.deletion
import technician.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=technician.models.get_categerious_image_path)),
                ('categories', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=technician.models.get_categerious_image_path)),
                ('sub_categories', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SubCategories',
            },
        ),
        migrations.CreateModel(
            name='TechnicianWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('longnitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('activate', models.BooleanField(default=False)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician.subcategories')),
            ],
        ),
    ]
